name: TWRP Funcional

on:
  push:
    branches:
      - main  # ou a branch que você quer usar para compilar
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Definindo a variável de ambiente para todo o job
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Configurando o Repositório
        uses: actions/checkout@v3  # Usando a vers??o mais recente do checkout

      - name: Instalando Dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

      - name: Instalando o Repo
        run: |
          # Baixa o script do repo
          wget https://storage.googleapis.com/git-repo-downloads/repo
          # Torna o script executável
          chmod a+x repo
          # Move para /usr/bin para facilitar o acesso
          sudo mv repo /usr/bin/

      - name: Verificar Espa??o em Disco
        run: df -h  # Exibe o uso de espa??o em disco antes da clonagem

      - name: Clonando o Repositório de Código-Fonte do TWRP
        run: |
          mkdir -p ~/twrp
          cd ~/twrp
          git init
          git remote add -f origin https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
          git config core.sparseCheckout true
          # Adicione os caminhos dos diretórios que você realmente precisa
          echo "device/*" >> .git/info/sparse-checkout  # Adapte isso ao que você precisa
          echo "vendor/*" >> .git/info/sparse-checkout  # Adapte isso ao que você precisa
          echo ".repo/*" >> .git/info/sparse-checkout  # Incluindo o diretório .repo
          # Sincroniza e atualiza
          git pull origin twrp-12.1

      - name: Clonando o Repositório do Dispositivo
        run: |
          cd ~/twrp
          # Clonando o repositório do dispositivo
          git clone https://github.com/boedhack99/device_xiaomi_ice-TWRP device/xiaomi/ice  # Substitua pelo repositório do seu dispositivo
          source build/envsetup.sh
          lunch twrp_ice  # Substitua "ice" pelo codename do seu dispositivo
          make recoveryimage

      - name: Salvando a Imagem Compilada
        uses: actions/upload-artifact@v3  # Usando a vers??o mais recente
        with:
          name: TWRP-Image
          path: ~/twrp/out/target/product/ice/recovery.img  # Substitua "ice" pelo codename do seu dispositivo
