name: TWRP Build

on:
  push:
    branches:
      - main  # ou a branch que voc¨º quer usar para compilar
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configurando o Reposit¨®rio
        uses: actions/checkout@v3  # Usando a vers0Š0o mais recente

      - name: Instalando Depend¨ºncias
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

      - name: Clonando o Reposit¨®rio de C¨®digo-Fonte do TWRP
        run: |
          mkdir -p ~/twrp
          cd ~/twrp
          git clone --depth=1 https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git .repo/manifests -b twrp-12.1
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j4

      - name: Clonando o Reposit¨®rio do Dispositivo
        run: |
          cd ~/twrp
          git clone --depth=1 https://github.com/matehus9/device_xiaomi_ice-TWRP.git device/xiaomi/ice -b twrp-12.1  # Clonando o seu fork
          source build/envsetup.sh  # Certifique-se de que este arquivo existe no seu fork
          lunch twrp_ice-eng  # Substitua "ice" pelo codename do seu dispositivo
          make recoveryimage

      - name: Salvando a Imagem Compilada
        uses: actions/upload-artifact@v3  # Usando a vers0Š0o mais recente
        with:
          name: TWRP-Image
          path: ~/twrp/out/target/product/ice/recovery.img  # Substitua "ice" pelo codename do seu dispositivo
